name: UBPorts Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl device-tree-compiler fakeroot flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils zstd -y --no-install-recommends
          sudo ln -sf /usr/bin/python2 /usr/bin/python

      - name: Clone UBPorts repo
        run: |
          git clone https://github.com/xiaomi-enuma-dev/ubuntu_touch_enuma

      - name: Run build
        run: |
          cd ubuntu_touch_enuma
          chmod +x build.sh
          ./build.sh -b workdir

      - name: Upload Build ZIPs
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-touch-builds
          path: ubuntu_touch_enuma/out/*.tar.xz
